src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    use PropertyTrait;
    use MetaTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 5, max: 255, minMessage: '10 caractères minimum', maxMessage: '255 caractères maximum')]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $text = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $url = null;

    #[ORM\Column(options: ['default' => 1])]
    private bool $available = true;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ProductType $type = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductResponse::class, cascade: ['persist', 'remove'])]
    private Collection $responses;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?City $city = null;

    #[ORM\ManyToMany(targetEntity: Feature::class, inversedBy: 'products', cascade: ['persist'])]
    #[ORM\OrderBy(['name' => 'ASC'])]
    private Collection $features;

    #[ORM\ManyToMany(targetEntity: Url::class, inversedBy: 'products', cascade: ['persist', 'remove'])]
    private Collection $urls;

    #[ORM\ManyToMany(targetEntity: Media::class, inversedBy: 'products', cascade: ['persist', 'remove'])]
    #[ORM\OrderBy(['order' => 'ASC'])]
    private Collection $medias;

    #[ORM\OneToMany(
        mappedBy: 'product',
        targetEntity: Plot::class,
        cascade: ['persist', 'remove'],
        orphanRemoval: true
    )]
    private Collection $plots;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $price = 0;

    public function __construct()
    {
        $this->responses = new ArrayCollection();
        $this->features = new ArrayCollection();
        $this->urls = new ArrayCollection();
        $this->medias = new ArrayCollection();
        $this->plots = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?ProductType
    {
        return $this->type;
    }

    public function setType(?ProductType $type): static
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, ProductResponse>
     */
    public function getResponses(): Collection
    {
        return $this->responses;
    }

    public function addResponse(ProductResponse $response): static
    {
        if (!$this->responses->contains($response)) {
            $this->responses->add($response);
            $response->setProduct($this);
        }

        return $this;
    }

    public function removeResponse(ProductResponse $response): static
    {
        if ($this->responses->removeElement($response)) {
            // set the owning side to null (unless already changed)
            if ($response->getProduct() === $this) {
                $response->setProduct(null);
            }
        }

        return $this;
    }

    public function isAvailable(): ?bool
    {
        return $this->available;
    }

    public function setAvailable(bool $available): static
    {
        $this->available = $available;

        return $this;
    }

    /**
     * @return ArrayCollection<int, Media>
     */
    public function getDocuments(int $typeId = MediaType::PICTURE, Media $mediaToExclude = null): ArrayCollection
    {
        return $this->getMedias()->filter(function (Media $media) use ($typeId, $mediaToExclude) {
            return $typeId === $media->getType()->getId() && (!$mediaToExclude || $mediaToExclude !== $media);
        });
    }

    /**
     * @return ArrayCollection<int, Media>
     */
    public function getPictures(Media $mediaToExclude = null): ArrayCollection
    {
        return $this->getDocuments(MediaType::PICTURE, $mediaToExclude);
    }

    public function getFirstPicture(): ?Media
    {
        foreach ($this->getMedias() as $media) {
            if (MediaType::PICTURE === $media->getType()->getId()) {
                return $media;
            }
        }

        return null;
    }

    public function getBrochures(): ArrayCollection
    {
        return $this->getDocuments(MediaType::BROCHURE);
    }

    public function getPlans(): ArrayCollection
    {
        return $this->getDocuments(MediaType::PLAN);
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCityZipcode(): ?string
    {
        return $this->getCity()?->getNameZipcode();
    }

    /**
     * @return Collection<int, Feature>
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Feature $feature): static
    {
        if (!$this->features->contains($feature)) {
            $this->features->add($feature);
        }

        return $this;
    }

    public function removeFeature(Feature $feature): static
    {
        $this->features->removeElement($feature);

        return $this;
    }

    /**
     * @return Collection<int, Url>
     */
    public function getUrls(): Collection
    {
        return $this->urls;
    }

    public function addUrl(Url $url): static
    {
        if (!$this->urls->contains($url)) {
            $this->urls->add($url);
        }

        return $this;
    }

    public function removeUrl(Url $url): static
    {
        $this->urls->removeElement($url);

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): static
    {
        if (!$this->medias->contains($media)) {
            $this->medias->add($media);
        }

        return $this;
    }

    public function removeMedia(Media $media): static
    {
        $this->medias->removeElement($media);

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): static
    {
        $this->text = $text;

        return $this;
    }

    /**
     * @return Collection<int, Plot>
     */
    public function getPlots(): Collection
    {
        return $this->plots;
    }

    public function addPlot(Plot $plot): static
    {
        if (!$this->plots->contains($plot)) {
            $this->plots->add($plot);
            $plot->setProduct($this);
        }

        return $this;
    }

    public function removePlot(Plot $plot): static
    {
        if ($this->plots->removeElement($plot)) {
            // set the owning side to null (unless already changed)
            if ($plot->getProduct() === $this) {
                $plot->setProduct(null);
            }
        }

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }
}

src/Controller/Front/ContactController.php
<?php

namespace App\Controller\Front;

use App\Controller\ArtemysController;
use App\Service\Customer\CustomerFormInterface;
use Symfony\Component\HttpFoundation\Response;

class ContactController extends ArtemysController
{
    public function index(CustomerFormInterface $customerForm): Response
    {
        $datas = $customerForm->save();
        if ($datas['isRedirect']) {
            return $this->redirectToRoute('front_contact');
        }

        return $this->render('front/contact.html.twig', $datas);
    }
}

src/Controller/Front/DocumentController.php
<?php

namespace App\Controller\Front;

use App\Controller\ArtemysController;
use App\Entity\Media;
use App\Entity\Product;
use App\Repository\ProductRepository;
use App\Service\Product\ProductFolderInterface;
use App\Service\Product\ProductMediaInterface;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

class DocumentController extends ArtemysController
{
    /**
     * @throws NonUniqueResultException
     */
    public function download(?Media $media): BinaryFileResponse|Response
    {
        if (null === $media) {
            return $this->goto404();
        }

        /** @var ProductRepository $repo */
        $repo = $this->em->getRepository(Product::class);
        $product = $repo->getProductByMedia($media);

        if (!$product) {
            return $this->goto404();
        }

        $order = 1;
        foreach ($product->getMedias() as $m) {
            if ($m->getType() !== $media->getType()) {
                continue;
            }
            if ($media === $m) {
                break;
            }
            ++$order;
        }

        $file = new File($media->getUrl());
        $filename = $media->getType()->getName() . ' ' . $order . '.' . $file->guessExtension();
        $response = new BinaryFileResponse($media->getUrl());
        $response->setContentDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            $filename
        );

        return $response;
    }

    public function downloadAll(
        ?Product $product,
        ProductMediaInterface $productMedia,
        ProductFolderInterface $productFolder
    ): Response {
        if (null === $product) {
            return $this->goto404();
        }

        $zip = new \ZipArchive();
        $zipName = 'artemys.zip';
        $zip->open('data/' . $zipName, \ZipArchive::CREATE);

        $folderPath = $productFolder
            ->set($product)
            ->getPath()
        ;
        $zip->addFile($folderPath, 'dossier.pdf');

        foreach ($productMedia->getDocumentsByProduct($product) as $type) {
            $folder = $type['name'];
            $zip->addEmptyDir($folder);
            foreach ($type['documents'] as $k => $doc) {
                $file = new File($doc['url']);
                $filename = $folder . ' ' . ($k + 1) . '.' . $file->guessExtension();
                $zip->addFile($doc['url'], $folder . '/' . $filename);
            }
        }
        $zip->close();

        $response = new Response();
        $response->headers->set('Cache-Control', 'private');
        $response->headers->set('Content-Type', 'application/zip');
        $response->headers->set('Content-Disposition', 'attachment;filename="' . $zipName . '"');
        $response->headers->set('Content-length', (string) \filesize('data/' . $zipName));
        $response->sendHeaders();
        $response->setContent(\file_get_contents('data/' . $zipName));
        \unlink('data/' . $zipName);

        return $response;
    }
}

src/Controller/Front/HomeController.php
<?php

namespace App\Controller\Front;

use App\Controller\ArtemysController;
use App\Entity\Media;
use App\Repository\PartnerRepository;
use App\Service\Front\HomeProductInterface;
use App\Service\Media\FrontThumbnailInterface;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Response;

class HomeController extends ArtemysController
{
    public function index(HomeProductInterface $homeProduct, PartnerRepository $partnerRepo): Response
    {
        return $this->render('front/index.html.twig', [
            'products' => $homeProduct->get(),
            'partners' => $partnerRepo->findBy(['active' => true]),
        ]);
    }

    public function image(
        string $token,
        string $filter,
        FrontThumbnailInterface $thumbGenerator
    ): BinaryFileResponse {
        $media = $this->em->getRepository(Media::class)->findOneBy(['token' => $token]);
        $url = $thumbGenerator->miniaturize($media->getUrl(), $filter);

        return $this->file($url);
    }
}

src/Controller/Front/ProductController.php
<?php

namespace App\Controller\Front;

use App\Controller\ArtemysController;
use App\Service\Map\MapInterface;
use App\Service\Product\ProductMediaInterface;
use App\Service\Slugger\SluggerUrlInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends ArtemysController
{
    public function index(
        string $typeSlug,
        string $productSlug,
        ProductMediaInterface $productMedia,
        SluggerUrlInterface $sluggerUrl,
        MapInterface $map
    ): Response {
        [$productType, $productTypeUrl] = $sluggerUrl->getProductType($typeSlug);
        [$product, $productUrl] = $sluggerUrl->getProduct($productSlug);

        if ($productType && $product) {
            $cities = $map
                ->init()
                ->setDatas(new ArrayCollection([$product]))
                ->getDatas()
            ;

            return $this->render('front/product.html.twig', [
                'product' => $product,
                'documents' => $productMedia->getDocumentsByProduct($product),
                'cities' => $cities,
            ]);
        }

        // Old urls
        if ($productTypeUrl && $productUrl) {
            return $this->redirectToRoute(
                'front_product',
                ['typeSlug' => $productTypeUrl, 'productSlug' => $productUrl],
                Response::HTTP_MOVED_PERMANENTLY
            );
        }

        return $this->goto404();
    }
}

src/Controller/Front/ProductTypeController.php
<?php

namespace App\Controller\Front;

use App\Controller\ArtemysController;
use App\Entity\ProductType;
use App\Service\Map\MapInterface;
use App\Service\Slugger\SluggerUrlInterface;
use Symfony\Component\HttpFoundation\Response;

class ProductTypeController extends ArtemysController
{
    public function index(string $typeSlug, SluggerUrlInterface $sluggerUrl, MapInterface $map): Response
    {
        /**
         * @var ProductType|null $productType
         * @var string           $redirectUrl
         */
        [$productType, $redirectUrl] = $sluggerUrl->getProductType($typeSlug);

        if ($productType) {
            $cities = $map
                ->init()
                ->setDatas($productType->getProducts(true))
                ->getDatas()
            ;

            return $this->render('front/product_type.html.twig', [
                'productType' => $productType,
                'products' => $productType->getProducts(true),
                'cities' => $cities,
            ]);
        }

        if ($redirectUrl) {
            return $this->redirectToRoute(
                'front_product_type',
                ['typeSlug' => $redirectUrl],
                Response::HTTP_MOVED_PERMANENTLY
            );
        }

        return $this->goto404();
    }
}

templates/front/card.html.twig
{% set col = col is defined ? col : 'col-12 col-md-6 col-xl-4' %}
{% set isIcon = isIcon is defined ? isIcon : true %}
{% set imgSize = imgSize is defined ? imgSize : 'thumb' %}
{% set justFirstPicture = justFirstPicture is defined ? justFirstPicture : false %}
<div class="row">
   {% for product in products %}
      {% set pictures = justFirstPicture ? [product.firstPicture] : product.pictures %}
      <div class="d-flex {{ col }} mb-4">
         <div class="card card-product js-card-product w100p" id="card-product-{{ product.token }}">
            <div class="card-body">
               <div class="card-product-header">
                  <a href="{{ path('front_product', {typeSlug: product.type.url, productSlug: product.url}) }}">
                     <div class="card-product-imgs">
                        {% for k, picture in pictures %}
                           <div class="card-product-img">
                              <img src="{{ asset(picture.url)|imagine_filter(imgSize) }}"
                                   class="js-card-product-img"
                                   alt="Image {{ k }} de {{ product.name }}"
                              >
                           </div>
                        {% endfor %}
                     </div>
                     <div class="card-product-bg"></div>
                     {% if pictures|length > 1 %}
                        <div class="card-product-arrows">
                           <div class="card-product-arrow js-product-left"><i class="fa fa-chevron-left"></i></div>
                           <div class="card-product-arrow js-product-right"><i class="fa fa-chevron-right"></i></div>
                        </div>
                        <div class="card-product-thumbs">
                           <ul>
                              {% for i in 0..(pictures|length - 1) %}
                                 <li class="card-product-thumb {{ loop.first ? 'active' : '' }}" data-index="{{ i }}">
                                    <span></span>
                                 </li>
                              {% endfor %}
                           </ul>
                        </div>
                     {% endif %}
                     <div class="card-product-link">Découvrir</div>
                  </a>
               </div>
               <div class="card-product-content">
                  <div class="card-product-title">{{ product.name }}</div>
                  <div class="card-product-city">{{ product.cityZipcode }}</div>
                  <div>{{ product.text|intro(200)|striptags }}</div>
               </div>
            </div>
            {% if isIcon and product.responses is defined %}
               <div class="card-footer">
                  {% for response in product.responses %}
                     <div class="text-center">
                        <div><i class="{{ response.question.icon }} c-6 fs24"></i></div>
                        <span class="fw-bolder">{{ response.value }}</span>
                     </div>
                  {% endfor %}
               </div>
            {% endif %}
         </div>
      </div>
   {% else %}
      Aucune offre pour le moment !
   {% endfor %}
</div>

templates/front/card_line.html.twig
{% set col = col is defined ? col : 'col-12 col-md-6 col-xl-4' %}
{% set isIcon = isIcon is defined ? isIcon : true %}
{% set imgSize = imgSize is defined ? imgSize : 'thumb' %}
{% set justFirstPicture = justFirstPicture is defined ? justFirstPicture : false %}
<div class="row" style="height:auto!important;max-height: 1000px;overflow-y: scroll">
{#   <div class="col mb20">#}
{#      <h2 class="fw300">Lorem ipsum dolor <br class="d-sm-none">#}
{#         <span class="fw900">consectetur adipisicing elit</span>#}
{#      </h2>#}
{#      <div class="text-italic c-6">Ab aliquam beatae consequatur, cum cupiditate dignissimos</div>#}
{#      <hr class="hr w20p mt30">#}
{#   </div>#}
   {% for product in products %}
      {% set pictures = justFirstPicture ? [product.firstPicture] : product.pictures %}
      <div class="d-flex col-12">
         <div class="card card-product js-card-product w100p no-shadow {{ not loop.last ? 'mb30' : 'mb0' }}" id="card-product-{{ product.token }}" style="box-shadow:none!important;min-height: auto!important;border-radius: 0!important;">
            <div class="card-body d-flex flex-row fs12">
               <div class="card-product-header " style="box-shadow:none!important;min-height: auto!important;height: auto!important;width:200px!important;border-radius: 0!important;">
                  <a href="{{ path('front_product', {typeSlug: product.type.url, productSlug: product.url}) }}" style="width: 100%;!important;">
                     <div class="card-product-imgs" style="box-shadow:none!important;border-radius: 0!important;">
                        {% for picture in pictures %}
                           <div class="card-product-img" style="box-shadow:none!important;border-radius: 0!important;">
                              <img src="{{ asset(picture.url)|imagine_filter(imgSize) }}" class="js-card-product-img h100">
                           </div>
                        {% endfor %}
                     </div>
                  </a>
               </div>
               <div class="card-product-content p0 pl20 " style="margin-left: auto; margin-right: auto;">
                  <div class="card-product-title d-flex justify-content-between align-items-center">
                     <span class="mr10">{{ product.name }}</span>
                     <span class="card-product-city fwn">{{ product.cityZipcode }}</span>
                  </div>
                  <div>{{ product.text|intro(200)|striptags }}</div>
               </div>
            </div>
            {#            {% if isIcon and product.responses is defined %} #}
            {#               <div class="card-footer"> #}
            {#                  {% for response in product.responses %} #}
            {#                     <div class="text-center"> #}
            {#                        <div><i class="{{ response.question.icon }} c-6 fs24"></i></div> #}
            {#                        <span class="fw-bolder">{{ response.value }}</span> #}
            {#                     </div> #}
            {#                  {% endfor %} #}
            {#               </div> #}
            {#            {% endif %} #}
         </div>
      </div>
   {% else %}
      Aucune offre pour le moment !
   {% endfor %}
</div>

templates/front/error404.html.twig
{% extends 'front/template.html.twig' %}

{% block breadcrumb %}
   <li class="breadcrumb-item">Oups !</li>
{% endblock %}

{% block header %}
<div id="slider-home">
   <div id="slider-slides">
      <img src="{{ asset('img/1.jpg')|imagine_filter('full') }}">
      <div id="contact-us">
         <a href="{{ path('front_contact') }}">
            <div id="contact-us-text"><span class="fw300">Nous</span> contacter</div>
            <div id="contact-us-btn">
               <div id="contact-us-icon">
                  <i class="fa fa-arrow-right"></i>
               </div>
            </div>
         </a>
      </div>
   </div>
</div>
{% endblock %}

{% block body %}
   <div class="container pt100 pb100 text-center">
      <div class="fw900 fs30">Oups</div>
      <div>Une erreur s'est produite</div>
      <a href="{{ path('front_index') }}" class="{{ HTML.btnShow }} mt20">Retour à l'accueil</a>
   </div>
{% endblock %}

templates/front/flash.html.twig
{# {{ dump(app.flashes) }} #}
{#<div class="container">#}
   {% for label, messages in app.flashes %}
      {% for message in messages %}
         <div class="alert alert-{{ label }} d-flex align-items-center">
            {{ message|nl2br }}
         </div>
      {% endfor %}
   {% endfor %}
{#</div>#}

templates/front/product.html.twig
{% extends 'front/template.html.twig' %}

{% block title %}
   {% if product.metaTitle %}
      {{ product.metaTitle }}
   {% else %}
      {{ product.name }} ({{ product.type.name }})
   {% endif %}
{% endblock %}
{% block metaDescription %}{{ product.metaDescription }}{% endblock %}
{% block metaKeywords %}{{ product.metaKeywords }}{% endblock %}

{# {% block header %} #}
{#   <div class="full-screen full-screen-50"> #}
{#      <img src="{{ asset(product.firstPicture.url)|imagine_filter('full') }}"> #}
{#   </div> #}
{# {% endblock %} #}
{% block header %}
   <div id="slider-home">
      <div id="slider-slides">
         <img src="{{ asset(product.firstPicture.url)|imagine_filter('full') }}">
         <div class="slider-titles">
            <div class="slider-title">Artemys
               <span class="fw300">Investissement</span>
            </div>
            <div class="slider-subtitle">{{ product.name }}
               <span class="ml5 mr5">/</span>{{ product.cityZipcode }}</div>
         </div>
      </div>
      <div id="contact-us">
         <a href="{{ path('front_contact') }}">
            <div id="contact-us-text">
               <span class="fw300">Nous</span>
               contacter
            </div>
            <div id="contact-us-btn">
               <div id="contact-us-icon">
                  <i class="fa fa-arrow-right"></i>
               </div>
            </div>
         </a>
      </div>
   </div>
{% endblock %}

{% block breadcrumb %}
   <li class="breadcrumb-item">
      <a href="{{ path('front_product_type', {typeSlug:product.type.url}) }}">
         {{ product.type.name }}
      </a>
   </li>
   <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
{% endblock %}

{% block body %}
   <div class="bg-gray">
      <div class="container pt50 pb50">
         <div class="d-sm-flex align-items-center mb40">
            <div>
               <h1>
                  <div class="product-subtitle">Notre terrain</div>
                  <div class="product-title">{{ product.name }}</div>
               </h1>
               <div class="fs18 c-6">{{ product.cityZipcode }}</div>
            </div>
         </div>
         <div class="row">
            <div class="col-12 col-xl-6 mb-5">
               <div class="fs18">
                  {{ product.text|raw }}
               </div>
            </div>
            <div class="d-block d-xl-none mt40"></div>
            <div class="col-12 col-xl-6 mb-5 documents">
               <div class="documents-back">
                  <img src="{{ asset('img/folder.png')|imagine_filter('thumb_all') }}" class="w75p">
               </div>
               <div class="documents-content">
                  <div class="documents-title mb-4">
                     Nos
                     <span>documents</span>
                     {% if documents|length %}
                        <a href="{{ path('front_documents', {token: product.token}) }}"
                           class="btn btn-md btn-outline-warning p1 pl5 pr5 border-1 fs14"
                        >
                           Tout télécharger
                        </a>
                     {% endif %}
                  </div>
                  <div class="documents-type">
                     {% if documents|length %}
                        {% for type in documents %}
                           <div class="pb-4">
                              <div class="fs20 mb10 fw900 text-primary">
                                 <span class="fs24 mr10"><i class="{{ type.icon }}"></i></span>
                                 {{ type.name }}
                              </div>
                              {% for key, doc in type.documents %}
                                 <a href="{{ path('front_document', {token: doc.token}) }}"
                                    class="btn btn-outline-secondary m5 p5 pl10 pr10 border-1 fs14"
                                    download
                                 >
                                    Télécharger {{ type.documents|length > 1 ? ' ' ~  (key + 1) : '' }}
                                 </a>
                              {% endfor %}
                           </div>
                        {% endfor %}
                     {% else %}
                        <div class="pb-4 text-muted">Aucun document actuellement</div>
                     {% endif %}
                  </div>
                  {#                  <div class="documents-folder"> #}
                  {#                     <i class="far fa-folder"></i> #}
                  {#                  </div> #}
               </div>
            </div>


         </div>
      </div>
   </div>

   {% include 'front/map_v2.html.twig' with {isMapListener: false} %}

   <div class="bg-gray position-relative">
      <div class="container pt50 pb50">
         <div class="mb50">
            <h2 class="fw300">Lorem ipsum dolor <br class="d-sm-none">
               <span class="fw900">consectetur adipisicing elit</span>
            </h2>
            <div class="text-italic c-6">Ab aliquam beatae consequatur, cum cupiditate dignissimos</div>
            <hr class="hr w20p mt30">
         </div>
         <div class="row">
            <div class="col-12 mb-4">
               <img src="{{ asset(product.firstPicture.url)|imagine_filter('big') }}" class="w100p radius15">
            </div>
            {% for picture in product.pictures %}
               <div class="col-6 col-md-4 col-lg-3 col-xl-2">
                  <a href="{{ asset(picture.url)|imagine_filter('big') }}" data-lightbox="roadtrip">
                     <img src="{{ asset(picture.url)|imagine_filter('thumb') }}" class="w100p radius5 mb-4">
                  </a>
               </div>
            {% endfor %}
         </div>
      </div>
   </div>


   {#   <div class=""> #}
   {#      <div class="container pt50"> #}
   {#         <div class="mb50"> #}
   {#            <h2 class="fw300">Lorem ipsum dolor <br class="d-sm-none"> #}
   {#               <span class="fw900">consectetur adipisicing elit</span> #}
   {#            </h2> #}
   {#            <div class="text-italic c-6">Ab aliquam beatae consequatur, cum cupiditate dignissimos</div> #}
   {#            <hr class="hr w20p mt30"> #}
   {#         </div> #}
   {#      </div> #}
   {#      <div class="d-flex flex-wrap"> #}
   {#         {% for picture in product.pictures %} #}
   {#            <div class="col-12 col-xl-6 overflow-hidden js-product-size"> #}
   {#               <a href="{{ path('front_document', {token: picture.token}) }}" data-lightbox="roadtrip"> #}
   {#                  <img src="{{ asset(picture.url)|imagine_filter('big') }}" class="w100p h100p object-fit-cover"> #}
   {#               </a> #}
   {#            </div> #}
   {#         {% endfor %} #}
   {#      </div> #}
   {#   </div> #}


   <div class="">
      <div class="container pt50">
         <div class="mb50">
            <h2 class="fw300">Lorem ipsum dolor <br class="d-sm-none">
               <span class="fw900">consectetur adipisicing elit</span>
            </h2>
            <div class="text-italic c-6">Ab aliquam beatae consequatur, cum cupiditate dignissimos</div>
            <hr class="hr w20p mt30">
         </div>
      </div>
      <div class="d-flex flex-wrap">
         {% for picture in product.pictures %}
            <div class="col-12 col-xl-6 overflow-hidden js-product-size">
               <a href="{{ asset(picture.url)|imagine_filter('big') }}" data-lightbox="roadtrip">
                  <img src="{{ asset( picture.url)|imagine_filter('big') }}" class="w100p h100p object-fit-cover">
               </a>
            </div>
         {% endfor %}
      </div>
   </div>
{% endblock %}